services:
  postgres:
    container_name: postgrescontainer
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Developer55*
      POSTGRES_DB: hasura_db  # Definir la base de datos inicial
    networks:
      - hasura-postgres-network
    ports:
      - "5432:5432"  # Puesto que PostgreSQL usa el puerto 5432 por defecto
    volumes:
      - "/c/Users/LENOVO/OneDrive/Documentos/DOCKER_APLICATIONS/VOLUMES/POSTGRES:/var/lib/postgresql/data"

  hasura:
    container_name: hasuracontainer
    image: hasura/graphql-engine
    restart: always
    depends_on:
      - postgres
    networks:
      - hasura-postgres-network
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Developer55*@postgres:5432/hasura_db  # Cambiar el puerto a 5432
      HASURA_GRAPHQL_ADMIN_SECRET: Developer55*  # Para el acceso al admin de Hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"  # Habilitar la consola de Hasura
    volumes:
      - "/c/Users/LENOVO/OneDrive/Documentos/DOCKER_APLICATIONS/VOLUMES/HASURA:/hasura-data"

networks:
  hasura-postgres-network:
    driver: bridge